config/routes.rb
Rails.application.routes.draw do
  resources :users  #, only: [:show, :new, :create, :destroy]
  resources :drinks #, only: [:index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  root to: 'static#home'

  get '/signup', to: 'users#new', as: 'signup'
  get '/login', to: 'sessions#new', as: 'login'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

  patch '/tab', to: "tab#update", as: :add_drink_to_tab

  # resources :users
  # resources :sessions, only: [:new, :create, :destroy]
  # root to: 'static_pages#home'
  # match '/signup',  to: 'users#new',            via: 'get'
  # match '/signin',  to: 'sessions#new',         via: 'get'
  # match '/signout', to: 'sessions#destroy',     via: 'delete'
  # match '/help',    to: 'static_pages#help',    via: 'get'
  # match '/about',   to: 'static_pages#about',   via: 'get'
  # match '/contact', to: 'static_pages#contact', via: 'get'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/drink.rb
class Drink < ApplicationRecord
  belongs_to :user
  # 
  # COCKTAILS = HTTParty.get("http://localhost:8000/api/v1/cocktails")
  # def self.all_drinks
  #   drinks = JSON.parse(COCKTAILS.body)
  #   drinks.each do |drink|
  #     Drink.create(drink_name: drink["name"], drink_)
  #   end
end

app/models/user.rb
class User < ApplicationRecord
  # validates :user_name, presence: true, uniqueness: true
  #
  # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #
  # validates :email, presence: true, length: { maximum: 255 },
  #                 format: { with: VALID_EMAIL_REGEX },
  #                 uniqueness: { case_sensitive: false }
  before_save { self.email = email.downcase }
  before_save :create_remember_token
  validates :user_name,  presence: true, length: { maximum: 50 }
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false }
  validates :age, numericality: { greater_than_or_equal_to: 21 }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :drinks
  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/application_controller.rb
=begin
def current_user
  # User.find would throw an error if we cannot find the user
  User.find_by({ id: session[:user_id] })
end

def logged_in?
  # nil is falsey in ruby
  # a user instance is truthy
  !!current_user
end

def authorized
  redirect_to login_path unless logged_in?
end

# def tab
#   session[:tab] ||= []
# end
#
# def add_drink_to_tab(drink_id)
#   tab << drink_id
# end
#
# def get_drinks_from_tab
#   @ordered_drinks = Drink.find(tab)
# end
#
# def count_ordered_drinks
#   get_drinks_from_tab.length
# end
#
# def set_drink_timeout
#
# end
=end

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorized #lock down this whole app
  # helper_method :current_user #i can call current_user from a view
  include SessionsHelper
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController
  # COCKTAILS = HTTParty.get('http://localhost:8000/api/v1/cocktails')
  # DRINKS = JSON.parse(COCKTAILS.body)
  before_action :find_drink, only: [:show]
  before_action :get_drinks_from_tab, only: [:index]

  def index
    @drinks = Drink.all
    # byebug
    render(:index)
  end


  def show
    render(:show)
  end

  private

  def find_drink
    @drink = Drink.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/controllers/tab_controller.rb
class TabController < ApplicationController

  def update
    add_drink_to_tab(params[:drink_id])
    flash[:success] = "Order: #{params[:drink_name]}"
    redirect_to drinks_path
    # byebug
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end


  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Virtual bar!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # def update
  #   @user.update(update_user_params)
  # end



  private

  # 💪 strong params
  def user_params
    params.require(:user).permit(:user_name, :email, :age, :password, :password_confirmation)
  end
  # 💪 strong params
  # def update_user_params
  #   params.require(:user).permit(:user_name,:email)
  # end

end # end UsersController class

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/drinks_helper.rb
module DrinksHelper
  include HTTParty
  # BASE_URI = "http://localhost:8000/api/v1/cocktails"
  # def api
  #   BASE_URI
  # end

  def get_drink_id(drink)
    HTTParty.get("http://localhost:8000/api/v1/cocktails/#{drink['id']}")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def authorized
    redirect_to login_path unless signed_in?
  end

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # def gravatar_for(user, options = { size: 200 })
  #   gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  #   size = options[:size]
  #   gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  #   image_tag(gravatar_url, alt: user.user_name, class: "gravatar")
  # end

end

app/views/drinks/index.erb
<div class="container">
  <div class="row">
    <div class="col-lg-10 mx-auto col-12 text-center mb-3">
      <h1 class="mt-0 text-primary">Our Menu</h1>
    </div>

    <div class="col-12 mt-4">
      <p class="lead text-center pb-4" style="color: #000;">Select your drink(s) to be tracked by your Virtual Bar!</p>

      <h3 class="text-center">Cocktails</h3>
      <hr class="accent my-5">
    </div>

    <div class="card-columns">
      <%= render "partials/drinks" %>
    </div>
  </div>
</div>

app/views/drinks/show.erb
<h1>Drinks#show</h1>

<p><%= @drink.drink_name %></p>

<%= link_to 'All drinks', drinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VirtualBar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/partials/_drinks.erb
<h4>Your Tab: </h4>
<ol>
  <% @ordered_drinks.each do |drink| %>
    <li> <%= drink.drink_name %> </li>
  <% end %>
</ol>

<% @drinks.map do |drink| %>
  <div class="card card-body">
    <span class="float-right font-weight-bold">$<%= (1..20).to_a.sample %></span>
    <h6 class="text-truncate"><%= link_to drink.drink_name, drink %></h6>
      <%= button_to "Add To Tab", add_drink_to_tab_path, method: :patch, params: { drink_id: drink.id, drink_name: drink.drink_name} %>
  </div>
<% end %>

app/views/partials/_error_messages.erb
<% if flash.length > 1%>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(flash[:errors].count, "error") %>.
    </div>
    <ul>
    <% flash[:errors].full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/partials/_flash.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
  <ul class="list-group">
    <li class="list-group-item list-group-item-danger"><%= flash[:errors] %></li>
  </ul>
  <% end %>
<% end%>

app/views/partials/_login.erb
<h1>Login</h1>
<%= render "partials/flash" %>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(:session, url: sessions_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", login_path %></p>
  </div>
</div>

app/views/partials/_profile.erb
<div class="container">
    <section class="d-flex align-items-center user-info">
      <!-- <h4 class="p-2 mr-2"></h4> -->
      <h1 class="m-3 display-2"><%= @user.user_name %></h1>

    </section>
    <% @user.drinks.each do |drink| %>
    <div class="card card-body">
      <h6 class="text-truncate"> <%= drink.drink_name %> </h6>
    </div>
    <% end %>
</div>
<%# <%= gravatar_for @user %> %>

app/views/partials/_signup.erb
<h1>Sign Up!</h1>
<%= render "partials/flash" %>
<%= form_for @user do |f| %>

  <div class="form-group">
    <%= f.label "Username" %>
    <%= f.text_field :user_name, class: 'form-control', placeholder: 'username' %>
  </div>

  <div class="form-group">
    <%= f.label "E-Mail" %>
    <%= f.text_field :email, class: 'form-control', placeholder: 'email' %>
  </div>

  <div class="form-group">
    <%= f.label "Age" %>
    <%= f.number_field :age, class: 'form-control', placeholder: 'age' %>
  </div>

  <div class="form-group">
    <%= f.label "Password" %>
    <%= f.password_field :password, class: 'form-control', placeholder: 'password'%>
  </div>

  <div class="form-group">
    <%= f.label "Confirmation" %>
    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'password' %>
  </div>

  <%=  f.submit class: 'btn btn-primary btn-lg' %>

<% end %>

app/views/partials/_user_drinks.erb
<% @user.drinks.get_drinks_from_tab.map do |drink| %>
  <div class="card card-body">
    <span class="float-right font-weight-bold">$<%= (1..20).to_a.sample %></span>
    <h6 class="text-truncate"><%= link_to drink.drink_name, drink %></h6>
  </div>
<% end %>

app/views/users/home.erb
<div class="container full-height align-middle">
  <div class="row align-items-center h-100">
    <div class="mx-auto">

      <h1 class="display-1">VIRTUAL BAR!</h1>

      <p class="lead">This is an amazing application inspired by flatirons own TCF <strong>Dick Ward</strong></p>

      <%= button_to "Sign Up", '/users/new', method: :get, class: 'btn btn-primary btn-lg' %>

      <%= button_to "Log In", '/users/login', method: :get, class: 'btn btn-primary btn-lg' %>
``
    </div>
  </div>
</div>

app/views/users/index.erb
<%= render "partials/profile" %>

app/views/users/new.erb
<div class="container">
    <%= render "partials/signup" %>
</div>

app/views/users/show.erb
<%= render "partials/profile" %>